// <auto-generated />
using System;
using DropThisSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DropThisSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315202633_onepluss")]
    partial class onepluss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.Property<int>("IdJewelry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJewelry"));

                    b.Property<int>("IdJewelryTip")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdStone")
                        .HasColumnType("int");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("NameJewelry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriceJewelry")
                        .HasColumnType("int");

                    b.HasKey("IdJewelry");

                    b.HasIndex("IdJewelryTip");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdStone");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.JewelryTip", b =>
                {
                    b.Property<int>("IdJewelryTip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJewelryTip"));

                    b.Property<string>("NameJewelryTip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdJewelryTip");

                    b.ToTable("JewelryTips");
                });

            modelBuilder.Entity("DropThisSite.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Proba")
                        .HasColumnType("int");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("DropThisSite.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("IdJewelry")
                        .HasColumnType("int");

                    b.Property<int>("IdStatusOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdJewelry");

                    b.HasIndex("IdStatusOrder");

                    b.HasIndex("IdUser");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DropThisSite.Models.StatusOrder", b =>
                {
                    b.Property<int>("IdStatusOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusOrder"));

                    b.Property<string>("NameStatusOrder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatusOrder");

                    b.ToTable("StatusOrders");
                });

            modelBuilder.Entity("DropThisSite.Models.Stone", b =>
                {
                    b.Property<int>("IdStone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStone"));

                    b.Property<string>("ColorStone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameStone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("WeightStone")
                        .HasColumnType("real");

                    b.HasKey("IdStone");

                    b.ToTable("Stones");
                });

            modelBuilder.Entity("DropThisSite.Models.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupplier"));

                    b.Property<string>("EmailSupplier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameSupplier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneSupplier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSupplier");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.HasOne("DropThisSite.Models.JewelryTip", "JewelryTip")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdJewelryTip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Material", "Material")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Stone", "Stone")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdStone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Supplier", "Supplier")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JewelryTip");

                    b.Navigation("Material");

                    b.Navigation("Stone");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DropThisSite.Models.Order", b =>
                {
                    b.HasOne("DropThisSite.Models.Jewelry", "Jewelry")
                        .WithMany("Orders")
                        .HasForeignKey("IdJewelry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("IdStatusOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");

                    b.Navigation("StatusOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.HasOne("DropThisSite.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.JewelryTip", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Material", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DropThisSite.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.Stone", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Supplier", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
