// <auto-generated />
using System;
using DropThisSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DropThisSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617025923_finally1234")]
    partial class finally1234
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DropThisSite.Models.ColorStoune", b =>
                {
                    b.Property<int>("IdColorStone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColorStone"));

                    b.Property<string>("ColorStone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdColorStone");

                    b.ToTable("ColorsStounes");
                });

            modelBuilder.Entity("DropThisSite.Models.Delivery", b =>
                {
                    b.Property<int>("IdDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDelivery"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.HasKey("IdDelivery");

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.Property<int>("IdJewelry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJewelry"));

                    b.Property<int>("IdJewelryTip")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdStone")
                        .HasColumnType("int");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameJewelry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriceJewelry")
                        .HasColumnType("int");

                    b.HasKey("IdJewelry");

                    b.HasIndex("IdJewelryTip");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdStone");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.JewelryTip", b =>
                {
                    b.Property<int>("IdJewelryTip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJewelryTip"));

                    b.Property<string>("NameJewelryTip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdJewelryTip");

                    b.ToTable("JewelryTips");
                });

            modelBuilder.Entity("DropThisSite.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Proba")
                        .HasColumnType("int");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("DropThisSite.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int?>("IdJewelry")
                        .HasColumnType("int");

                    b.Property<int>("IdStatusOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdJewelry");

                    b.HasIndex("IdStatusOrder");

                    b.HasIndex("IdUser");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdJewelry")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdJewelry");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DropThisSite.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DropThisSite.Models.StatusOrder", b =>
                {
                    b.Property<int>("IdStatusOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusOrder"));

                    b.Property<string>("NameStatusOrder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatusOrder");

                    b.ToTable("StatusOrders");
                });

            modelBuilder.Entity("DropThisSite.Models.Stone", b =>
                {
                    b.Property<int>("IdStone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStone"));

                    b.Property<int>("IdColorStone")
                        .HasColumnType("int");

                    b.Property<string>("NameStone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("WeightStone")
                        .HasColumnType("real");

                    b.HasKey("IdStone");

                    b.HasIndex("IdColorStone");

                    b.ToTable("Stones");
                });

            modelBuilder.Entity("DropThisSite.Models.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupplier"));

                    b.Property<string>("EmailSupplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameSupplier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneSupplier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSupplier");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DropThisSite.Models.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWarehouse"));

                    b.Property<string>("NameWarehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdWarehouse");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("DropThisSite.Models.WarehouseItem", b =>
                {
                    b.Property<int>("IdWarehouseItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWarehouseItem"));

                    b.Property<int>("IdJewelry")
                        .HasColumnType("int");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdWarehouseItem");

                    b.HasIndex("IdJewelry");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("WarehouseItems");
                });

            modelBuilder.Entity("DropThisSite.Models.Delivery", b =>
                {
                    b.HasOne("DropThisSite.Models.Order", "Order")
                        .WithOne("Deliveries")
                        .HasForeignKey("DropThisSite.Models.Delivery", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.HasOne("DropThisSite.Models.JewelryTip", "JewelryTip")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdJewelryTip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Material", "Material")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Stone", "Stone")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdStone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Supplier", "Supplier")
                        .WithMany("Jewelries")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JewelryTip");

                    b.Navigation("Material");

                    b.Navigation("Stone");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DropThisSite.Models.Order", b =>
                {
                    b.HasOne("DropThisSite.Models.Jewelry", "Jewelry")
                        .WithMany("Orders")
                        .HasForeignKey("IdJewelry");

                    b.HasOne("DropThisSite.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("IdStatusOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");

                    b.Navigation("StatusOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropThisSite.Models.OrderItem", b =>
                {
                    b.HasOne("DropThisSite.Models.Jewelry", "Jewelry")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdJewelry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DropThisSite.Models.Stone", b =>
                {
                    b.HasOne("DropThisSite.Models.ColorStoune", "ColorStoune")
                        .WithMany("Stones")
                        .HasForeignKey("IdColorStone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorStoune");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.HasOne("DropThisSite.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DropThisSite.Models.WarehouseItem", b =>
                {
                    b.HasOne("DropThisSite.Models.Jewelry", "Jewelry")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("IdJewelry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropThisSite.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DropThisSite.Models.ColorStoune", b =>
                {
                    b.Navigation("Stones");
                });

            modelBuilder.Entity("DropThisSite.Models.Jewelry", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Orders");

                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("DropThisSite.Models.JewelryTip", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Material", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Order", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DropThisSite.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DropThisSite.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.Stone", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.Supplier", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DropThisSite.Models.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DropThisSite.Models.Warehouse", b =>
                {
                    b.Navigation("WarehouseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
